drop table if exists hibernate_sequence;
drop table if exists ob_order;
drop table if exists ob_order_product;
drop table if exists ob_product;
drop table if exists ob_seat;
drop table if exists ob_user;
create table hibernate_sequence (next_val bigint);
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table ob_order (order_id bigint not null, name varchar(255), total_price integer not null, customer_id bigint, seat_id bigint, primary key (order_id));
create table ob_order_product (order_product_id bigint not null, amount integer not null, count integer not null, order_id bigint, product_id bigint, primary key (order_product_id));
create table ob_product (product_id bigint not null, detail varchar(255), name varchar(255), photo_url varchar(255), price integer not null, primary key (product_id));
create table ob_seat (seat_id bigint not null, name varchar(255), primary key (seat_id));
create table ob_user (customer_id bigint not null, customer_name varchar(255), primary key (customer_id));
alter table ob_order add constraint FKa819hvqhvas4girelelcwbxi8 foreign key (customer_id) references ob_user (customer_id);
alter table ob_order add constraint FK70xs4jce7n1q8w5s8wvopdd1 foreign key (seat_id) references ob_seat (seat_id);
alter table ob_order_product add constraint FK5eusf4u0e7nk8shkbn0qv6pl foreign key (order_id) references ob_order (order_id);
alter table ob_order_product add constraint FKa7otcw8uc130udi3q59ange9q foreign key (product_id) references ob_product (product_id);
alter table ob_order_product add constraint FKwn47hg4h6dyswpj9us1phv5v foreign key (order_product_id) references ob_order (order_id);